name: py-bmw
channels:
  - conda-forge
dependencies:
  - python=3.9
  - erddapy
  - geopandas
  - jupyter
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - matplotlib-base
  - nbval
  - pandas
  - pyworms
  - xarray